# Generated by Django 3.2.9 on 2021-12-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='long_description',
            field=models.TextField(blank=True),
        ),
    ]
